### ISSUE TITLE
MELPA dependency

### ISSUE THREAD

**Issue by Ambrevar** [Somelauw/evil-org-mode#28]
The current dependency list on MELPA marks MELPA's Org as a dependency.

The package says Org 8.0 is enough. (Emacs 25 has a newer version.)

Is it possible to remove the MELPA's Org dependency?
Some users don't want an additional Org installed on their computer on every update:

- Those who don't mind Emacs embedded version of Org.

- Those who want org-plus-contrib for additional features like org-agenda.

- Those with slow connections or who mind heavy packages.

**Comment by Somelauw** [comment]
> The current dependency list on MELPA marks MELPA's Org as a dependency.

This dependency was added because some functions from org-element are used, which didn't exist until org 7.9.2 However, even if the minimum version is set to 7.9.2, I'm not sure that we aren't using other more recent functions from org.

> The package says Org 8.0 is enough. (Emacs 25 has a newer version.)

Are you saying that Emacs tries to install Org from melpa even when the org included (by Emacs 25) is higher and should already work with org?

**Comment by Ambrevar** [comment]
yes!
