### ISSUE TITLE
Keys are not bound

### ISSUE THREAD

**Issue by Linuus** [Somelauw/evil-org-mode#54]
A while ago `tab` stopped working correctly (could not fold/unfold drawers). It turned out that other people had the same issue: https://www.reddit.com/r/emacs/comments/aidi7r/cant_fold_logbook/
To fix it, I need to have this:
```
    (with-eval-after-load 'evil
      (evil-define-key 'normal outline-mode-map (kbd "<tab>") #'org-cycle)
      (evil-define-key 'normal outline-mode-map (kbd "TAB") #'org-cycle))
```

I also noticed that other keys are not bound correctly as well, like `)` is bound to `evil-forward-sentence-begin` instead of `evil-org-forward-sentence` etc.

What could cause these issues? Does evil-org need an update or have I screwed up my config? :)

My evil-org config looks like this:
```
  (use-package evil-org
    :ensure t
    :after org
    :config
    (require 'evil-org-agenda)
    (with-eval-after-load 'evil
      (evil-define-key 'normal outline-mode-map (kbd "<tab>") #'org-cycle)
      (evil-define-key 'normal outline-mode-map (kbd "TAB") #'org-cycle))
    (evil-org-agenda-set-keys)
    (add-hook 'org-mode-hook 'evil-org-mode)
    (add-hook 'evil-org-mode-hook
              (lambda ()
                (evil-org-set-key-theme))))
```

**Comment by aidenscott2016** [comment]
I don't think it's just you. I have the same problems setting up emacs from scratch.

**Comment by wedens** [comment]
The same problem occurs with `<return>` bindings. I think `kbd "RET"` should also be mapped.

**Comment by Somelauw** [comment]
Mapping RET sounds okay.

For tab I'm considering a defcustom. The problem is that it conflicts with `C-i`, which is an unrelated Evil shortcut.

**Comment by Somelauw** [comment]
Set `evil-want-C-i-jump` to `nil` for tab

**Comment by myshevchuk** [comment]
In my situation, when I just open an org file `TAB` is bound depending on the context to `+fold/toggle` when the point is on a collapsed outline or `evil-jump-item` elsewhere, including an outline just unfolded with `+fold/toggle`, so that it would not collapse again. 

As soon as I execute such evil commands as `f`, `s`, `O`, `o`, `dd`, `TAB` is rebound to `org-cycle`. What seems strange to me is that this happens in every newly visited org file, that is those commands have been executed elsewhere and packages already been loaded. 

Restarting org-mode, switching it off and on, toggling evil-org-mode have no effect. Simple navigation commands like `j`, `k`, `gg`, `G` do not have any trigger effect either.

**Comment by Somelauw** [comment]
Although this is a common issue, I believe the clean solution is in unbinding `TAB` in evil.
