### ISSUE TITLE
emacs hangs after evil-org-open-below in numbered list

### ISSUE THREAD

**Issue by dwuggh** [Somelauw/evil-org-mode#77]
I'm using emacs 27.0.91 with spacemacs develop branch, which integrates this package. On spacemacs, emacs hangs which I described in [spacemacs's #13684](https://github.com/syl20bnr/spacemacs/issues/13684):
#### Reproduction:

- Start Emacs
- create a .org file
- write something like
``` org
    * foo
      - bar
        1. put your cursor at this line
            barfoo
        2. foofoo
```
- place the cursor at line "put your cursor at this line"
- press "o"(evil-open-below)
- and then emacs freezes.

I haven't tested with a pure environment(e.g. only emacs, evil and this package), but i think it's reproducable. 

I also track it down with edebug and found out emacs freezed when somewhere around
```elisp
(defun org-list-write-struct (struct parents &optional old-struct)
    ;; ...
    ;; 6. Apply structure modifications to buffer.
    (org-list-struct-apply-struct struct old-struct))
```

**Comment by duianto** [comment]
It seems to be caused by something in Spacemacs, because I'm unable to reproduce it with just Emacs, `evil` and `evil-org`.

The expected new list item is added when `o` is pressed:
```
* foo
  - bar
    1. put your cursor at this line
    2. 
        barfoo
    3. foofoo
```

### System info
evil-org-20200601.1855
evil-20200530.659
Emacs:
- GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
- GNU Emacs 27.0.90 (build 1, x86_64-w64-mingw32) of 2020-03-01

Windows 1903

**Comment by dwuggh** [comment]
Thanks for testing, I'll close it for now.
